nslab/nslab/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from xinwen import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('xinwen.urls',namespace='xinwen'))
]

nslab/xinwen/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),

    url(r'^titles/$',views.titles,name='titles'),

    url(r'^titles/(\d+)/$',views.title,name='title')
]

nslab/xinwen/models.py
from django.db import models

class Title(models.Model):
    text = models.CharField(max_length=200)
    url = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.text

class Content(models.Model):
    title=models.ForeignKey(Title)
    text=models.TextField()

    def __str__(self):
        return self.text[:50]

nslab/xinwen/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Title

def index(request):
    return render(request,'xinwen/index.html')

def titles(request):
    titles = Title.objects.all()
    context = {'titles':titles}
    return render(request,'xinwen/titles.html',context)

def title(request,title_id):
    title = Title.objects.get(id=title_id)
    content = title.content_set.all()
    context={'title':title,'contents':content}
    return render(request,'xinwen/title.html',context)

nslab/xinwen/templates/xinwen/base.html
<p>
  <a href="{% url 'xinwen:index'%}">xinwen</a>
  <a href="{% url 'xinwen:titles'%}">titles</a>
</p>

{% block content %}{% endblock content%}

nslab/xinwen/templates/xinwen/index.html
{% extends "xinwen/base.html" %}

{% block content %}
  <p></p>
{% endblock content %}

nslab/xinwen/templates/xinwen/title.html
{% extends "xinwen/base.html" %}

{% block content %}

  <p>Titles:{{title}}</p>

  <ul>
    {% for content in contents %}
      <li>
        <p>{{ content.text|linebreaks}}</p>
      </li>
    {% empty %}
      <li>empty</li>
    {% endfor %}
  </ul>

{% endblock content %}

nslab/xinwen/templates/xinwen/titles.html
{% extends "xinwen/base.html" %}

{% block content %}

  <p>Titles</p>

  <ul>
    {% for title in titles %}
      <li>
        <a href="{% url 'xinwen:title' title.id %}">{{title}}</a>
      </li>
    {% empty %}
      <li>empty</li>
    {% endfor %}
  </ul>

{% endblock content %}